# Generated by Django 5.0.6 on 2024-08-20 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user1', '0002_user_reg_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employement_type', models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self employed')], max_length=15)),
                ('pannumber', models.CharField(max_length=10)),
                ('panimage', models.FileField(upload_to='pan')),
                ('incomeproof', models.FileField(upload_to='income')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user1.user_reg')),
            ],
        ),
    ]
