# Generated by Django 5.0.6 on 2024-08-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laf',
            name='employement_type',
            field=models.CharField(choices=[('salaried', 'Salaried'), ('self_employed', 'Self employed')], max_length=60),
        ),
    ]
