# Generated by Django 5.0.6 on 2024-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_laf_employement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='laf',
            name='loanamount',
            field=models.BigIntegerField(null=True),
        ),
    ]
