# Generated by Django 5.0.6 on 2024-08-24 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_laf_loanamount'),
    ]

    operations = [
        migrations.CreateModel(
            name='admini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('empid', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
