# Generated by Django 5.0.6 on 2024-08-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_admini'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loandisbursed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dateofapproval', models.DateField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.laf')),
            ],
        ),
    ]
