# Generated by Django 5.0.6 on 2024-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_loandisbursed'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandisbursed',
            name='EMI',
            field=models.IntegerField(default=13843),
            preserve_default=False,
        ),
    ]
