# Generated by Django 5.0.6 on 2024-09-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_emipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='emipayment',
            name='No_of_Payments',
            field=models.IntegerField(null=1),
            preserve_default=1,
        ),
    ]
