# Generated by Django 5.0.6 on 2024-09-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_emipayment_no_of_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('empid', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='emipayment',
            name='No_of_Payments',
            field=models.IntegerField(default=0),
        ),
    ]
