# Generated by Django 5.0.6 on 2024-09-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0010_employee_address_employee_dob_employee_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laf',
            name='empid',
            field=models.IntegerField(null=True),
        ),
    ]
