# Generated by Django 5.0.6 on 2024-08-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='password',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
